import Head from 'next/head';

import CardGrid from '../components/Cards/CardGrid';

export default function Home({ events }) {
	return (
		<div>
			<Head>
				<title>Evently</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CardGrid events={events} />
		</div>
	);
}

export async function getStaticProps() {
	// Fetch the products
	const res = await fetch(`${process.env.API_ENDPOINT}/events`);
	const events = await res.json();

	//Return the products as props
	return {
		props: {
			events
		}
	};
}
