import Head from 'next/head';
import Link from 'next/link';
import { makeStyles } from '@material-ui/core/styles';
import { Container } from '@material-ui/core';
import Typography from '@material-ui/core/Typography';

import Hero from '../components/Hero/Hero';
import CardGrid from '../components/Cards/CardGrid';

const useStyles = makeStyles((theme) => ({
	header: {
		padding: '0px 6px'
	}
}));

export default function Home({ events }) {
	const classes = useStyles();
	return (
		<div>
			<Head>
				<title>Evently</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container className={classes.header} maxWidth="lg">
				<Hero />
				<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
					<Typography style={{ color: '#98A0A7' }} variant="h4">
						Upcoming Events
					</Typography>
					<Link href="/">
						<a style={{ textDecoration: 'none' }}>
							<Typography color="primary">View more</Typography>
						</a>
					</Link>
				</div>
			</Container>

			<CardGrid events={events} />
		</div>
	);
}

export async function getStaticProps() {
	// Fetch the products
	const res = await fetch(`${process.env.API_ENDPOINT}/events`);
	const events = await res.json();

	//Return the products as props
	return {
		props: {
			events
		}
	};
}
